### ISSUE TITLE
respect utf8

### ISSUE THREAD

**Issue by KES777** [frioux/DBIx-Class-DeploymentHandler#65]
described here: https://github.com/jjn1056/DBIx-Class-Migration/issues/108

**Comment by mohawk2** [comment]
@KES777 Thanks for reporting this on here and SQLT as asked. Sadly I am entirely sure this is an SQLT/Moose interaction (which seems to zap imported things, which may explain the zapping of `utf8` only on Moose DBIC classes), so unless you provide steps that prove the problem is in DH, no action is possible.

Closing until that is provided.

**Comment by KES777** [comment]
@mohawk2 Hi. Steps were provided. 3 additional tests were written for DBICM, DBICDH and SQLT. See the linked PR 82 
I hope they will help to understand the problem better.
